name = "orboro-net"
compatibility_date = "2026-04-05"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "orboro-db"
database_id = "REPLACE_WITH_REAL_DATABASE_ID"
migrations_dir = "migrations"
