name = "orboro-net"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-04-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.1

[assets]
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "orboro-db"
database_id = "7fe68e1c-ce42-40a6-ae78-3bb674d6ad0f"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "orboro-net-media"
